"""Added picture to user

Revision ID: 513854416fad
Revises: 92ad2918cc30
Create Date: 2024-04-17 11:39:33.233534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513854416fad'
down_revision = '92ad2918cc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
